---
title: "Expulsos"
editor: visual
lang: "pt"
format:
  html:
    code-fold: true
    code-summary: "mostrar o código"
    code-overflow: wrap
execute:
  warning: false
  message: false
---

```{r}
#| warning: false
#| message: false
library(readxl)
library(tidyverse)
library(janitor)
library(lubridate)
library(tidyverse)
library(purrr)
library(plotly)
library(knitr)
library(kableExtra)
library(deflateBR)
library(DescTools)
library(zoo)
library(stringr)
library(DT)
```

```{r}

expulsos <- read_excel("expulsos/expulsos.xlsx") %>% clean_names()

expulsos <- expulsos %>% mutate(ano = year(data_publicacao))
```

```{r}

```

```{r}
`%notin%` <- Negate(`%in%`)
```

```{r}

expulsos   %>% group_by( categoria_da_sancao) %>% count() %>% arrange(desc(n)) %>% head()  %>% kable()
```

```{r}
expulsos %>% group_by(ano ) %>% count() %>% arrange(desc(ano))  %>% kable()
```

```{r}

expulsos %>% group_by(nome_do_sancionado, cpf_ou_cnpj_do_sancionado) %>% mutate(nome_do_sancionado = str_sub(nome_do_sancionado, end = 10L)) %>% count() %>% arrange(desc(n)) %>% head() %>% kable()


orgao <- c("REITORIA","SETOR DE BENEFÍCIOS","FACULDADE DE ENFERMAGEM","SERVIÇO DE GESTÃO ADMINISTRATIVA", "EQUIPE DE ATENDIMENTO AO CONTRIBUINTE","FACULDADE DE ODONTOLOGIA","GABINETE","DELEGACIA 04","OUVIDORIA")

expulsos %>% filter(orgao_de_lotacao %in% orgao)  %>% group_by(  orgao_de_lotacao,orgao_sancionador) %>% count() %>% arrange(desc(n)) %>% head()  %>% kable()



expulsos %>% group_by(cargo_efetivo) %>% count() %>% arrange(desc(n)) %>% head() %>% kable()



```
