# https://stackoverflow.com/questions/73628379/rendering-many-connected-quarto-documents

data_formatada <- function(x){parse_date_time(x, "dmy")}


lapso <- function(x,y){
  time_length(difftime(x,y), "years")
}

funcao_data_base <- function(df){data_base <- paste0(max(df$ano), "-",max(df$mes, na.rm = TRUE),"-31")}

funcao_cargos <- function(df){
  df<- df %>%  mutate(
    descricao_01 = case_when(
      startsWith(descricao_cargo, "ASG - ") ~ str_remove_all(descricao_cargo, "ASG - "),
      startsWith(descricao_cargo, "ATA") ~ str_remove_all(descricao_cargo, "ATA "),
      startsWith(descricao_cargo, "ATA-") ~ str_remove_all(descricao_cargo, "ATA-"),
      startsWith(descricao_cargo, "ATA - ") ~ str_remove_all(descricao_cargo, "ATA - "),
      startsWith(descricao_cargo, "ATA - TECNICO") ~  "TECNICO",
      startsWith(descricao_cargo, "ATA - PROGRAMADOR") ~ "PROGRAMADOR",
      startsWith(descricao_cargo, "ASO-") ~  str_remove_all(descricao_cargo, "ASO-"),
      startsWith(descricao_cargo, "TNS - ") ~  str_remove_all(descricao_cargo, "TNS - "),
      startsWith(descricao_cargo, "TNS-") ~  str_remove_all(descricao_cargo, "TNS-"),
      startsWith(descricao_cargo, "TNS-") ~  str_remove_all(descricao_cargo, "TNS-"),
      startsWith(descricao_cargo, "ASM-") ~  str_remove_all(descricao_cargo, "ASM-"),
      startsWith(descricao_cargo, "ASM-") ~  str_remove_all(descricao_cargo, "ASM-"),
      startsWith(descricao_cargo, "TEM ") ~  str_remove_all(descricao_cargo, "TEM "),
      startsWith(descricao_cargo, "TEC ") ~  "TECNICO",
      startsWith(descricao_cargo, "TNS ") ~  str_remove_all(descricao_cargo, "TNS "),
      startsWith(descricao_cargo, "TIn ") ~  str_remove_all(descricao_cargo, "TIn "),
      startsWith(descricao_cargo, "PROIND - ") ~  str_remove_all(descricao_cargo, "PROIND - "),
      startsWith(descricao_cargo, "PROSAL - ") ~  str_remove_all(descricao_cargo, "PROSAL - "),
      startsWith(descricao_cargo, "PROESU - ") ~  str_remove_all(descricao_cargo, "PROESU - "),
      startsWith(descricao_cargo, "PROF ") ~  "PROFESSOR",
      .default = descricao_cargo),
    descricao_01 =str_replace (  descricao_01, "-", " "),
    cargo_termo =word ( descricao_01 ,1),
    cargo = case_when(
      startsWith(descricao_cargo,   "AAD")~ "AUXILIAR",
      startsWith(descricao_cargo,   "AUX")~ "AUXILIAR",
      startsWith(descricao_cargo,   "AUG")~ "AUXILIAR",
      str_detect(descricao_cargo,   "AUXILIAR DE")~ "AUXILIAR",
      startsWith(descricao_cargo, "AG ")~ "AGENTE",
      startsWith(descricao_cargo, "PESQ")~ "PESQUISADOR",
      str_detect(descricao_cargo, "ANALI")~ "ANALISTA",
      str_detect(descricao_cargo, "TSE-")~ "TECNICO",
      str_detect(descricao_cargo, "EMPREGADO SERPRO")~ "EMPREGADO SERPRO",
      str_detect(descricao_cargo, "ENGENHEIRO-AREA")~ "ENGENHEIRO",
      str_detect(descricao_cargo, "FARMACEUTICO-")~ "FARMACEUTICO",
      str_detect(descricao_cargo, "FARMECEUTICO-")~ "FARMACEUTICO",
      str_detect(descricao_cargo, "ASSIST")~ "ASSISTENTE",
      str_detect(descricao_cargo, "ESP EM")~ "ESPECIALISTA",
      str_detect(descricao_cargo, "ESP REG")~ "ESPECIALISTA",
      str_detect(descricao_cargo, "ESP POL")~ "ESPECIALISTA",
      str_detect(descricao_cargo, "ATD-MS")~ "EQUIPE HOSPITALAR",
      startsWith(descricao_cargo, "TECNOL")~ "TECNOLOGO",
      startsWith(descricao_cargo, "ATA - TECNICO")~ "TECNICO",
      str_detect(descricao_cargo, "-TECNICO")~ "TECNICO",
      startsWith(descricao_cargo, "ATA - PROGRAMADOR")~ "PROGRAMADOR",
      startsWith(descricao_cargo, "MEDICINA")~ "MEDICO",
      startsWith(descricao_cargo, "ENFERMAGEM")~ "ENFERMEIRO",
      startsWith(descricao_cargo, "RELACOES PUBLICAS")~ "RELACOES PUBLICAS",
      startsWith(descricao_cargo, "ESPEC ")~ "ESPECIALISTA",
      startsWith(descricao_01, "PRIMEIRO")~ descricao_01,
      startsWith(descricao_01, "SEGUNDO")~ descricao_01,
      startsWith(descricao_01, "MINISTRO")~ descricao_cargo,
      startsWith(descricao_cargo, "OP ")~ "OPERADOR",
      startsWith(descricao_cargo, "ARTIF")~ "ARTIFICE",
      startsWith(descricao_cargo, "AUD FEDERAL")~ "AUDITOR",
      startsWith(descricao_cargo, "CUX")~ descricao_01,
      startsWith(descricao_01, "ASSIT")~ "ASSISTENTE",
      startsWith(descricao_cargo, "ATO -")~ "ASSISTENTE",
      startsWith(descricao_cargo, "CALDEREIRO")~ "CALDEIREIRO",
      startsWith(descricao_cargo, "CENOTECNICA")~ "CENOTECNICO",
      startsWith(descricao_cargo, "CINEGRAFIA")~ "CINEGRAFISTA",
      startsWith(descricao_cargo, "CONTRA REGRA")~ "CONTRA REGRA",
      startsWith(descricao_cargo, "CONTRA MESTRE")~ "CONTRA MESTRE",
      startsWith(descricao_cargo, "COMPRADORA")~ "COMPRADOR",
      startsWith(descricao_cargo, "PEDAGOGA")~ "PEDAGOGO",
      startsWith(descricao_cargo, "RECREADORA")~ "RECREADOR",
      startsWith(descricao_cargo, "PROD EXEC TV - RADIO E MIDIAS DIGITAIS")~ "PRODUTOR EXEC TV - RADIO E MIDIAS DIGITAIS",
      startsWith(descricao_cargo, "CONDUCAO")~ "MOTORISTA",
      startsWith(descricao_cargo, "PROFIS TEC ESPEC LINGUAGEM SINAIS")~ "ESPECIALISTA LINGUAGEM SINAIS",
      startsWith(descricao_cargo, "COORDEN")~ "COORDENADOR",
      startsWith(descricao_cargo, "PROFIS DE NIVEL OPERACIONAL")~ "APOIO",
      startsWith(descricao_cargo, "PROFIS DE EDUCACAO FISICA")~ "PROFISSIONAL DE EDUCACAO FISICA",
      startsWith(descricao_cargo, "OF ARTES GRAFICAS")~ "OF ARTES GRAFICAS",
      startsWith(descricao_cargo, "OF MANUTENCAO")~ "OF MANUTENCAO",
      startsWith(descricao_cargo, "COZINHEIRA")~ "COZINHEIRO",
      startsWith(descricao_cargo, "TERCEIRO")~ descricao_cargo,
      startsWith(descricao_01, "CONTRA REGRA")~ "CONTRA-REGRA",
      startsWith(descricao_cargo, "CONTRAMESTRE")~ "CONTRA-MESTRE",
      startsWith(descricao_cargo, "ECONOMO")~ "ECONOMISTA",
      startsWith(descricao_cargo, "T P ECONOMIA III")~ "ECONOMISTA",
      startsWith(descricao_cargo, "PROG APLICACOES III")~ "PROGRAMADOR",
      startsWith(descricao_cargo, "T ASS ADM")~ "TECNICO",
      startsWith(descricao_cargo, "OPER ESPECIALIZADO")~ "OPERADOR",
      startsWith(descricao_cargo, "MEDICO VETERINARIO")~ descricao_cargo,
      startsWith(descricao_cargo, "PROGAMADOR")~ "PROGRAMADOR",
      startsWith(descricao_cargo, "ESTATISTICA")~ "ESTATISTICO",
      startsWith(descricao_cargo, "PROF SERV OPERACIONAIS")~"SERVICOS OPERACIONAIS IV",
      startsWith(descricao_cargo, "CARGO EM EXTINCAO")~ "CARGO EM EXTINCAO",
      startsWith(descricao_cargo, "SALVA-VIDAS")~ "SALVA-VIDAS",
      startsWith(descricao_cargo, "FISC")~ "FISCAL",
      startsWith(descricao_cargo, "VICE-PRESIDENTE DA REPUBLICA")~ "VICE-PRESIDENTE DA REPUBLICA",
      startsWith(descricao_cargo, "PRESIDENTE DA REPUBLICA")~"PRESIDENTE DA REPUBLICA",
      startsWith(descricao_cargo, "JORNALISMO")~ "JORNALISTA",
      startsWith(descricao_cargo, "VISITADOR SANITARIO")~ "VISITADOR SANITARIO",
      startsWith(descricao_cargo, "MAQ AUXLIAR ")~ "AUXILIAR",
      startsWith(descricao_cargo, "INSP")~ "INSPETOR",
      startsWith(descricao_cargo, "MOCO DE MAQUINAS")~ "MOÇO DE MAQUINAS",
      startsWith(descricao_cargo, "ASO-ASSI")~ "ASSISTENTE",
      startsWith(descricao_cargo, "ENGENHARIA DE SOFTWARE")~ "ENGENHEIRO",
      str_detect(descricao_cargo, "ADMINISTRADOR") | startsWith(descricao_cargo, "ADMINISTRACAO " )~ "ADMINISTRADOR",
      descricao_cargo %in% c("MDT-MEDICO","MEDICO-AREA","MDT-MEDICO DO TRABALHO") ~ "MEDICO",
      .default = cargo_termo))
}

