---
title: "Painel RS"
editor: visual
lang: "pt"
format:
  html:
    code-fold: true
    code-summary: "mostrar o código"
    code-overflow: wrap
execute:
  warning: false
  message: false
  error: false
  freeze: auto  # re-render only when source changes  
---

```{r bibliotecas}
#| warning: false
#| message: false
#| error: false
library(readxl)
library(tidyverse)
library(janitor)
library(lubridate)
library(tidyverse)
library(purrr)
library(plotly)
library(knitr)
library(kableExtra)
library(deflateBR)
library(DescTools)
library(zoo)
library(stringr)
library(DT)
library(stringr)
library(scales)
library(ggthemes)

```

```{r funcoes_e_opcoes}

# negar %in%
`%notin%` <- Negate(`%in%`)

# formato dos numeros
myNumFmt <- as.fmt(digits=0, big.mark=".")

options(scipen = 999)

options(DT.options = list(pageLength = 10, fontSize = "70%", language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese.json')))
```

## Tratamento

```{r}
library(readxl)


sof_rs <- read_excel("rs/sof_rs.xlsx") %>% clean_names() 


# sof_rs <- sof_rs %>% select(-ano, - marcador, -ano_referencia)



separar <- function(x){str_split_fixed (x, " - ",2) }


sof_rs_clean <-   sof_rs[3:18] %>% map(separar) %>% data.frame()

sof_rs <- cbind(sof_rs_clean, sof_rs[20:24])






```

```{r}
tg_rs <- read_excel("rs/tg_rs.xlsx") %>% clean_names()

tg_rs <- tg_rs %>% select( - item_informacao)

names(sof_rs) <- colnames(tg_rs)


sof_rs <- sof_rs %>% mutate(base= "sof")
tg_rs <- tg_rs %>% mutate(base = "tg")

dados <- rbind(sof_rs,tg_rs)
```

```{r}
# sof_rs %>% group_by(plano_orcamentario_codigo_po) %>% summarise(sof_dotacao_atualizada= sum(( dotacao_atualizada), na.rm = TRUE))
# 
# tg_rs %>% group_by(plano_orcamentario_codigo_po) %>% summarise(tg_dotacao_atualizada= sum(dotacao_atualizada, na.rm = TRUE))
# 
# comparacao <- left_join(sof_rs %>% group_by(plano_orcamentario_codigo_po) %>% summarise(sof_dotacao_atualizada= sum(( dotacao_atualizada), na.rm = TRUE)),tg_rs %>% group_by(plano_orcamentario_codigo_po) %>% summarise(tg_dotacao_atualizada= sum(dotacao_atualizada, na.rm = TRUE)))%>% replace(is.na(.), 0) %>% mutate(diferenca = sof_dotacao_atualizada-tg_dotacao_atualizada )
# 
# datatable(comparacao )%>% formatRound(c("sof_dotacao_atualizada", "tg_dotacao_atualizada", "diferenca"), 0, mark = ".", dec.mark = ",")
# 
# 
# 
# sof_empenhado <- sof_rs %>% group_by(plano_orcamentario_codigo_po) %>% summarise(sof_despesas_empenhadas= sum(( despesas_empenhadas), na.rm = TRUE))
# 
# tg_empenhado <- tg_rs %>% group_by(plano_orcamentario_codigo_po) %>% summarise(tg_despesas_empenhadas= sum(despesas_empenhadas, na.rm = TRUE))
# 
# comparacao <- left_join(sof_empenhado,tg_empenhado)%>% replace(is.na(.), 0) %>% mutate(diferenca = sof_despesas_empenhadas-tg_despesas_empenhadas )
# 
# datatable(comparacao )%>% formatRound(c("sof_despesas_empenhadas", "tg_despesas_empenhadas", "diferenca"), 0, mark = ".", dec.mark = ",")
```

```{r}


# datatable(dados %>%
#             filter (plano_orcamentario_codigo_po == "CP20") %>%
#             group_by(unidade_orcamentaria_codigo, acao_governo_codigo,funcao_governo_codigo, base) %>%
#             summarise(dotacao_atualizada = sum(dotacao_atualizada, na.rm = TRUE)) %>%
#             pivot_wider(names_from = base, values_from = dotacao_atualizada) %>%
#             mutate(diferenca = sof-tg) %>%
#             filter(diferenca !=0) %>%
#             arrange(diferenca))%>%
#   formatRound(c("sof", "tg", "diferenca"), 2, mark = ".", dec.mark = ",")
```

## Dotação inicial

```{r}
datatable(
  dados %>%
    group_by(plano_orcamentario_codigo_po,
             orgao_uge_orgao_maximo_codigo,
             unidade_orcamentaria_codigo,
             acao_governo_codigo,
             funcao_governo_codigo,
             subfuncao_governo_codigo,
             resultado_eof_codigo, base) %>%
    summarise(dotacao_atualizada = sum(dotacao_atualizada, na.rm = TRUE)) %>%
    pivot_wider(
      names_from = base,
      values_from = dotacao_atualizada) %>%
    mutate(diferenca = sof-tg) %>%
    filter(diferenca != 0) %>%
    arrange((diferenca)))%>%
  formatRound(c("sof", "tg", "diferenca"), 0, mark = ".", dec.mark = ",")

```

## Despesas empenhadas

```{r}
datatable(
  dados %>%
    group_by(plano_orcamentario_codigo_po, base) %>%
    summarise(despesas_empenhadas = sum(despesas_empenhadas, na.rm = TRUE)) %>%
    pivot_wider(
      names_from = base,
      values_from = despesas_empenhadas) %>%
    mutate(diferenca = sof-tg) %>%
    filter(diferenca != 0) %>%
    arrange((diferenca)))%>%
  formatRound(c("sof", "tg", "diferenca"), 0, mark = ".", dec.mark = ",")
```

```{r}
datatable(dados %>% filter (plano_orcamentario_codigo_po == "CP20") %>% group_by(unidade_orcamentaria_codigo, acao_governo_codigo,funcao_governo_codigo, base) %>% summarise(despesas_empenhadas = sum(despesas_empenhadas, na.rm = TRUE)) %>% pivot_wider(names_from = base, values_from = despesas_empenhadas) %>% mutate(diferenca = sof-tg) %>% filter(diferenca !=0) %>% arrange((diferenca)))%>% formatRound(c("sof", "tg", "diferenca"), 0, mark = ".", dec.mark = ",")
```
