---
title: "Pensionistas Siape"
editor: visual
lang: "pt"
format:
  html:
    code-fold: true
    code-summary: "mostrar o código"
    code-overflow: wrap
execute:
  warning: false
  message: false
---

```{r}
#| warning: false
#| message: false
library(readxl)
library(tidyverse)
library(janitor)
library(lubridate)
library(tidyverse)
library(purrr)
library(plotly)
library(knitr)
library(kableExtra)
library(deflateBR)
library(DescTools)
library(zoo)
library(stringr)
library(DT)
library(stringr)
```

```{r}

pensionistas_siape_cadastro <- read_delim("servidores/servidores/pos_2020/pensionistas_siape/202311_Cadastro.csv", 
    delim = ";", escape_double = FALSE, locale = locale(date_names = "pt", 
        decimal_mark = ",", grouping_mark = ".", 
        encoding = "Latin1"), trim_ws = TRUE) %>% clean_names()%>% mutate(nome_id = str_c(str_sub(nome, start = 1L, end = 4L), " - ",id_servidor_portal), cpf_instituidor = paste0(str_sub( cpf_instituidor_pensao,  start = 5L, end = -4L),"-",str_sub( nome_instituidor_pensao,   start = 1L, end = 5L)))


pensionistas_siape_remuneracao <- read_delim("servidores/servidores/pos_2020/pensionistas_siape/202311_Remuneracao.csv", 
    delim = ";", escape_double = FALSE, locale = locale(date_names = "pt", 
        decimal_mark = ",", grouping_mark = ".", 
        encoding = "Latin1"), trim_ws = TRUE) %>% clean_names() %>% mutate( nome_id = str_c(str_sub(nome, start = 1L, end = 4L), " - ",id_servidor_portal))

```

```{r}

pensionistas_siape_cadastro %>% group_by(cpf_instituidor) %>% count() %>% arrange(desc(n)) %>% head(20) %>% kable()



```

```{r}
tabela_pensionista_siape <- left_join(pensionistas_siape_remuneracao %>% select(ano,mes,id_servidor_portal, nome, cpf, nome_id, remuneracao_apos_deducoes_obrigatorias_r),pensionistas_siape_cadastro )






tabela_pensionista_siape <- tabela_pensionista_siape %>% mutate(inicio = year(parse_date_time(data_inicio_pensao,"dmy")))
```

```{r}
setdiff(pensionistas_siape_cadastro %>% select(nome_id), tabela_pensionista_siape %>% select(nome_id))


setdiff( tabela_pensionista_siape %>% select(nome_id),pensionistas_siape_cadastro %>% select(nome_id))

(nrow(pensionistas_siape_cadastro)-nrow(tabela_pensionista_siape))


(nrow(pensionistas_siape_cadastro)-nrow(pensionistas_siape_remuneracao))




```

```{r}
pensionistas_siape_cadastro %>% filter (nome_id == "Sigi - -11") %>% select(nome, cpf_instituidor_pensao)

pensionistas_siape_cadastro %>% group_by(cpf_instituidor) %>% count() %>% filter(n>1) %>% arrange(desc(n)) %>% head(10)%>% kable()


pensionistas_siape_cadastro %>% group_by(cpf_instituidor) %>% count() %>% filter(n>1) %>% arrange(desc(n))  %>%  group_by(n) %>% count()%>% kable()



pensionistas_siape_cadastro %>% filter(cpf_instituidor != "NA-Sem i")%>% group_by(cpf_instituidor) %>% count() %>% filter(n>9) %>% arrange(desc(n)) %>% head(10)%>% kable()
```

```{r}
tabela_pensionista_siape %>% group_by(nome_id) %>% count() %>% filter(n>1) %>%arrange(desc(n)) %>% head(50) %>%  kable()

`%notin%` <- Negate(`%in%`)
```

```{r}







```

```{r}
# tabela_pensionista_siape %>% filter( cpf_instituidor == "477.767-CILDO DE ASSIS SILVA")%>% summarise(valor = sum(remuneracao_apos_deducoes_obrigatorias_r)) %>% arrange(desc(valor)) %>% head() %>% kable()



tabela_pensionista_siape %>%filter(cpf_instituidor != "NA-Sem informação") %>% group_by(  nome_id) %>% summarise(valor = max((remuneracao_apos_deducoes_obrigatorias_r))) %>% arrange(desc(valor)) %>% head(20) %>% kable( format.args = list(big.mark = ".", decimal.mark = ","))
```

```{r}

tabela_pensionista_siape %>% mutate(ano = year(data_inicio_pensao)) %>% group_by(inicio) %>% summarise(valor = max(remuneracao_apos_deducoes_obrigatorias_r)) %>% arrange(desc(valor)) %>% kable( format.args = list(big.mark = ".", decimal.mark = ","))


tabela_pensionista_siape %>% mutate(ano = year(data_inicio_pensao)) %>% group_by(nome_id, inicio) %>% summarise(valor = max(remuneracao_apos_deducoes_obrigatorias_r)) %>% group_by(inicio) %>% summarise(valor = sum(valor/1000000000)) %>% arrange(desc(valor)) %>% adorn_totals()


```

```{r}
p <- ggplot(tabela_pensionista_siape %>% mutate(ano = year(data_inicio_pensao)) %>% group_by(nome_id, inicio) %>% summarise(valor = max(remuneracao_apos_deducoes_obrigatorias_r)) %>% group_by(inicio) %>% summarise(valor = sum(valor/1000000000)) %>% mutate(acumulado= cumsum(valor)), aes(x=inicio, y=acumulado)) +
    geom_line()    # Use hollow circles

ggplotly(p)


p <- ggplot(tabela_pensionista_siape %>% mutate(ano = year(data_inicio_pensao)) %>% group_by(nome_id, inicio) %>% summarise(valor = max(remuneracao_apos_deducoes_obrigatorias_r)) %>% group_by(inicio) %>% summarise(valor = sum(valor/1000000000)) %>% mutate(acumulado= cumsum(valor)), aes(x=inicio, y=valor)) +
    geom_line()    # Use hollow circles

ggplotly(p)


p <- ggplot(tabela_pensionista_siape %>% group_by(inicio) %>% summarise(n = n()) %>% mutate(acumulado = cumsum(n)), aes(x=inicio, y=acumulado)) +
    geom_line()    # Use hollow circles

ggplotly(p)


p <- ggplot(tabela_pensionista_siape %>% group_by(inicio) %>% summarise(n = n()) %>% mutate(acumulado = cumsum(n)), aes(x=inicio, y=n)) +
    geom_line()    # Use hollow circles

ggplotly(p)



```

```{r}
p <- ggplot(tabela_pensionista_siape %>% group_by( tipo_pensao)    %>% summarise(valor = sum(remuneracao_apos_deducoes_obrigatorias_r)) , aes(x=valor, y= tipo_pensao )) +
    geom_col()    # Use hollow circles

ggplotly(p)
```

```{r}
tabela_pensionista_siape %>% group_by( descricao_cargo_instituidor_pensao)    %>% summarise(valor = sum(remuneracao_apos_deducoes_obrigatorias_r)) %>% arrange(desc(valor)) %>% head(10) %>% kable( format.args = list(big.mark = ".", decimal.mark = ","))


tabela_pensionista_siape %>% group_by( descricao_cargo_instituidor_pensao)    %>% summarise(valor = sum(remuneracao_apos_deducoes_obrigatorias_r)) %>% arrange(desc(valor)) %>% head(20) %>% kable( format.args = list(big.mark = ".", decimal.mark = ","))

tabela_pensionista_siape %>% group_by( descricao_cargo_instituidor_pensao)    %>% summarise(valor = mean(remuneracao_apos_deducoes_obrigatorias_r)) %>% arrange(desc(valor)) %>% tail(20) %>% kable( format.args = list(big.mark = ".", decimal.mark = ","))


tabela_pensionista_siape %>% group_by( descricao_cargo_instituidor_pensao)    %>% summarise(valor = mean(remuneracao_apos_deducoes_obrigatorias_r)) %>% arrange(desc(valor)) %>% head(20) %>% kable( format.args = list(big.mark = ".", decimal.mark = ","))
```

```{r}
tabela_pensionista_siape %>% group_by( regime_juridico_instituidor_pensao)    %>% summarise(valor = round( sum(remuneracao_apos_deducoes_obrigatorias_r ))) %>% arrange(desc(valor)) %>% head(10) %>% kable( format.args = list(big.mark = ".", decimal.mark = ","))



tabela_pensionista_siape %>% group_by(situacao_vinculo)    %>% summarise(valor = round( sum(remuneracao_apos_deducoes_obrigatorias_r ))) %>% arrange(desc(valor)) %>% head(10) %>% kable( format.args = list(big.mark = ".", decimal.mark = ","))
```

```{r}

p <- ggplot(tabela_pensionista_siape %>%  filter(tipo_pensao == "Filho (a) / Menor sob guarda / Enteado (a)" ) %>% group_by(  inicio)    %>% summarise(valor = sum(remuneracao_apos_deducoes_obrigatorias_r)), aes(x=inicio, y=valor)) +
    geom_line()    # Use hollow circles

ggplotly(p)

tabela_pensionista_siape %>%  group_by(  nome_id)    %>% count() %>% arrange(desc(n)) %>% head(100) %>% kable()
```
